Signup
GSM-MSG/GAUTH-frontend pull request #5
Opened 2022-12-07 14:51 UTC by jjaejjae12

* 회원가입 페이지 퍼블리싱
* 회원가입 요청 기능 구현
* 회원가입 개인정보 동의서 퍼블리싱
* 회원가입 정규식 추가
* 회원가입 요청후 대기 시 모달 추가
* 회원가입 프로필 이미지 추가 기능 구현

2022-12-08 10:31 UTC, chanwoo00106 commented
<img width="181" alt="스크린샷 2022-12-08 오후 7 28 55" src="https://user-images.githubusercontent.com/57276315/206423791-d1bf7076-a184-4a7f-8891-7f5e21be403d.png">
이거 디자인이 원래 이런가요?<br />
배경색 때문에 글자가 많이 어둡게 보여요

2022-12-08 10:33 UTC, chanwoo00106 commented
pr 크기가 너무 큰 것 같아요 이러면 리뷰 해주는 사람이 많이 힘들 수 있어서 다음부턴 크기를 줄이는게 좋을 것 같아요

2022-12-08 10:40 UTC, chanwoo00106 commented on src/components/SignUpPage/index.tsx
> +						<defs>
혹시 defs가 뭔지 알 수 있을까요?

2022-12-08 10:40 UTC, chanwoo00106 commented on src/components/SignUpPage/index.tsx
> +	const SignUp = async () => {
이 함수가 사용되지 않고 있는 것 같은데 확인해 주세요

2022-12-08 10:43 UTC, chanwoo00106 commented
node 버전을 .nvm이라는 곳에 적으면 좋을 것 같아

2022-12-08 10:57 UTC, chanwoo00106 commented on src/components/SignUpPage/PrivacyConsent.tsx
> +					<li> 연락처 :010 2850 3235, s21073@gsm.hs.kr</li>
형우 개인정보는 왜 여기 있는지 알 수 있니?

2022-12-09 00:46 UTC, jjaejjae12 commented on src/components/SignUpPage/PrivacyConsent.tsx
> +					<li> 연락처 :010 2850 3235, s21073@gsm.hs.kr</li>
MSG 노션 gauth 개인정보 처리방침에 정리 되어있는 데로 작성 했어

2022-12-09 00:50 UTC, jjaejjae12 commented on src/components/SignUpPage/PrivacyConsent.tsx
> +	`;
스타일 분리 했어

2022-12-09 02:13 UTC, jjaejjae12 commented
.nvm에 버전을 적으라는 말이 뭘 하라는건지 모르겠어요

2022-12-09 13:02 UTC, chanwoo00106 commented
구글링

2022-12-09 13:14 UTC, chanwoo00106 commented on src/components/SignUpPage/index.tsx
> +	const SignUp = async () => {
서버 통신이 완벽하게 된 다음에 pr을 날려야 하지 않나?

2022-12-09 13:14 UTC, chanwoo00106 commented on yarn.lock
> +>>>>>>> 15d8db5 (회원가입페이지 퍼블리싱)
여기 뭔가 이상한데???

2022-12-09 13:14 UTC, chanwoo00106 commented on yarn.lock
> +>>>>>>> 15d8db5 (회원가입페이지 퍼블리싱)
여기도

2022-12-09 13:14 UTC, chanwoo00106 commented on src/components/SignUpPage/WaveWrapper.tsx
> +import * as SVG from '../../../public/svg';
나중에 absolute url 검색해봐

2022-12-12 03:25 UTC, jjaejjae12 commented on src/components/SignUpPage/index.tsx
> +						<defs>
[React Wavify](https://www.npmjs.com/package/react-wavify) 라는 파도 애니메이션 라이브러리 여서 바로 적었어

2022-12-12 06:51 UTC, jjaejjae12 commented on yarn.lock
> +>>>>>>> 15d8db5 (회원가입페이지 퍼블리싱)
저번에 pull받다가 코드 날라가서 그거 복구하면서 생긴거 같긴한데... yarn init 하고 다시 설치해서 해결했어

2022-12-12 06:52 UTC, jjaejjae12 commented on yarn.lock
> +>>>>>>> 15d8db5 (회원가입페이지 퍼블리싱)
여기도 똑같이 지워졌어

2022-12-15 13:56 UTC, chanwoo00106 commented on src/components/LoginPage/SideWave.tsx
> +  const waveRef = useRef<any>();
any가...

2022-12-18 23:44 UTC, jjaejjae12 commented on src/components/LoginPage/SideWave.tsx
> +  const waveRef = useRef<any>();
그부분은 경민이가 고친다고 해가지고

2022-12-20 04:15 UTC, jjaejjae12 commented on src/components/SignUpPage/index.tsx
> +	const SignUp = async () => {
다음부터 통신 체크 후 pr날릴께

2022-12-20 05:20 UTC, chanwoo00106 approved these changes
모달 같은 경우 react portal 로 하면 좋을 것 같음

2022-12-20 05:23 UTC, kangkong0805 approved these changes

2022-12-20 05:25 UTC, jjaejjae12 commented
서버통신 방금 다 오류 없이 끝넸는데 이거까지 commit날리고 merge할까?

2022-12-21 02:46 UTC, chanwoo00106 requested changes

2022-12-21 02:46 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +          profileUrl: typeof data == 'string' ? data : '',
```suggestion
          profileUrl: data ? data : null,
```
형우왈 : 빈 문자열 보단 null 이 좋대

2022-12-21 02:46 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +            window.location.replace('/login');
이것 보단 navigate가 더 좋을 것 같은데...

2022-12-21 02:46 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +export default function AuthenticationCheck({
함수명의 의도를 알 수가 없어요

함수명은 주석을 달지 않아도 알 수 있게 지어야합니다

2022-12-21 02:48 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +          profileUrl: typeof data == 'string' ? data : '',
확인

2022-12-21 02:48 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +            window.location.replace('/login');
수정할게

2022-12-21 02:50 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +export default function AuthenticationCheck({
다시 지어볼게

2022-12-21 02:51 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +}
component 안에 component는 좀 아닌듯;;

2022-12-21 02:53 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +}
그럼 {}로 감싸서 하나로 묶을까?

2022-12-21 03:00 UTC, chanwoo00106 requested changes

2022-12-21 03:00 UTC, chanwoo00106 commented on src/lib/API.tsx
> +// );
이 주석들은 뭐야

2022-12-21 03:00 UTC, chanwoo00106 commented on src/lib/API.tsx
> +  baseURL: 'http://10.82.18.111:8080/',
baseUrl 같은 경우는 dotenv에서 관리하는게 좋지 않을까?

2022-12-21 10:24 UTC, chanwoo00106 commented on src/lib/API.tsx
> +// );
그럼 이 pr 경민이랑 같이 하는 거야?

2022-12-21 10:26 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +          profileUrl: typeof data == 'string' ? data : '',
이거는 add suggestion to batch 누르면 바로 적용됨

2022-12-21 10:26 UTC, jjaejjae12 commented on src/lib/API.tsx
> +// );
아니 경민이는 login 브랜치에서 고치는 중

2022-12-21 10:27 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +}
;;

당연히 컴포넌트로 따로 빼야지

2022-12-21 10:27 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +          profileUrl: typeof data == 'string' ? data : '',
확인

2022-12-21 10:30 UTC, chanwoo00106 commented on .env
> +NEXT_PUBLIC_ENV_DATA="http://10.82.18.111:8080/"
영재야 나는 왜 환경변수를 볼 수 있는거야?

2022-12-21 10:30 UTC, baekteun commented on .env
> +NEXT_PUBLIC_ENV_DATA="http://10.82.18.111:8080/"
니 환경변수 쩔더라ㅋㅋ

2022-12-21 10:31 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +}
담고 있는 내용이 많지도 않고 따로 별 기능이 있는것도 아니여서 걍 묶어서 쓰는게 좋을듯 나도 처음에 왜 저렇게 쓴지 모르겠네..

2022-12-21 10:41 UTC, jjaejjae12 commented
안됬네

2022-12-21 10:54 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
`Gauth-accessToken`와 `Gauth-refreshToken`의 경우 오타가 있을 수 있으니 상수로 관리하는 게 좋을 듯

2022-12-21 10:56 UTC, kangkong0805 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
ㅇㅋ

2022-12-21 11:10 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
확인

2022-12-21 11:26 UTC, jjaejjae12 commented on .env
> +NEXT_PUBLIC_ENV_DATA="http://10.82.18.111:8080/"
고침

2022-12-21 11:26 UTC, jjaejjae12 commented on src/lib/API.tsx
> +  baseURL: 'http://10.82.18.111:8080/',
확인

2022-12-21 11:27 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
now merge time?

2022-12-21 11:38 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
<img width="444" alt="image" src="https://user-images.githubusercontent.com/81688137/208896775-3de80275-f759-4cd4-ba32-f4a25bf5b341.png">

2022-12-21 11:47 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
상수경로를 어디에 하는게 좋을까요?

2022-12-21 12:09 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +}
저러면 가독성 측면에서 그렇게 좋아보이지는 않으니깐 좀 쪼개면 좋을 것 같은데?

2022-12-21 12:11 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +import { accessToken, refreshToken } from '../../lib/Tokken';
Tokken

2022-12-21 12:11 UTC, chanwoo00106 commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
왜 2.5초 후에 redirect를 하는거야?

2022-12-21 12:13 UTC, baekteun commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
회원가입 완료 후 모달 바깥쪽 클릭하거나, 2.5초 뒤에 redirect 시킨다는데?

2022-12-21 23:13 UTC, jjaejjae12 commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
잠시 후 이동 문구이길레 잠시 후 이동하게 만들었는데 바로 이동하게 만들까?

2022-12-21 23:14 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +import { accessToken, refreshToken } from '../../lib/Tokken';
수정할게

2022-12-21 23:14 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +}
확인

2022-12-22 00:11 UTC, chanwoo00106 commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
굳이 2.5초를 기다릴 필요가 있을까?
어떤 애니메이션이라도 있어?

2022-12-22 00:19 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +          profileUrl: typeof data == 'string' ? data : '',
...

2022-12-22 00:21 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +import { accessToken, refreshToken } from '../../lib/Tokken';
했으면서 왜 안됨?

2022-12-22 00:24 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +      localStorage.setItem('Gauth-refreshToken', data.refreshToken);
그건 너희가 정하는 거지

2022-12-22 00:25 UTC, chanwoo00106 commented on src/lib/API.tsx
> +  baseURL: process.env.NEXT_PUBLIC_ENV_DATA,
환경변수 이름이 data면 안에 무슨 값이 들어있는 지 파악이 어려워
변수명은 되도록이면 할당된 값의 의미를 살릴 수 있는 이름으로 지어야해

2022-12-22 00:28 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +export default function AuthenticationCheck({
다시 지어서 무슨 이름이 되었는지 알려줘

2022-12-22 09:14 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +export default function AuthenticationCheck({
AuthenticationCheck => SendVerifyEmail

2022-12-22 09:15 UTC, jjaejjae12 commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
아니 딱히 애니메이션은 없고 그냥 바로 페이지 이동하게 바꾸는 게 좋을듯

2022-12-22 09:19 UTC, baekteun commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
바로 이동하기 하면 관리자 승인 기다리셈 모달이 없어지잖

2022-12-22 09:20 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +import { accessToken, refreshToken } from '../../lib/Tokken';
이제 했어

2022-12-22 09:21 UTC, jjaejjae12 commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
그럼 1초 정도로 짧게 보여주고 이동하게 바꾸는게 좋을까?

2022-12-22 09:50 UTC, jjaejjae12 commented on src/components/SendVerifyEmail/index.tsx
> +          }, 2500);
redirect하는 이유가 회원가입 하고 로그인 해야 서비스 이용할수 있으니깐 회원가입후 로그인 페이지로 이동 시키는 거임

2022-12-22 09:57 UTC, jjaejjae12 commented on src/lib/API.tsx
> +  baseURL: process.env.NEXT_PUBLIC_ENV_DATA,
NEXT_PUBLIC_ENV_DATA => NEXT_PUBLIC_BASE_URL

2022-12-22 09:58 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +}
컴포넌트 분리했어

2022-12-22 14:04 UTC, chanwoo00106 commented on src/components/AuthenticationCheck/index.tsx
> +export default function AuthenticationCheck({
이메일을 확인하는 거니깐 VerifyEmail이라고 해도 되지 않을까?
SendVerifyEmail은 동사, 동사, 명사 니깐 좀 별로임

2022-12-22 14:08 UTC, jjaejjae12 commented on src/components/AuthenticationCheck/index.tsx
> +export default function AuthenticationCheck({
저 컴포넌트에서 메일 전송이랑 체크를 같이 해서 SendVerifyEmail로 짖기는 했는데 결과적을 메일 확인이 목적이니깐  VerifyEmail로 고칠게

2022-12-22 14:11 UTC, chanwoo00106 reviewed
src/components/SignUpPage/index.tsx 이 부분 이거 ㅈㄴ 복잡한데 나중에 react-hook-form 을 적용하면 코드가 엄청 깔끔해 질거임

2022-12-22 14:22 UTC, jjaejjae12 commented on src/components/SignUpPage/index.tsx
> +                    onChange={(e) => changeHandler(e)}
확인

2022-12-22 14:29 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +                }}
난 안 써보긴 했는데 input 태그에 pattern이라는 게 있어서 정규식으로 검증을 할 수 있음

2022-12-22 14:29 UTC, chanwoo00106 commented on src/components/LoginPage/style.ts
> +  position: absolute;
여기에 position absolute가 숨어 있었네
반응형이 잘 된다면 상관 없는데 되도록이면 지우자

2022-12-22 14:36 UTC, jjaejjae12 commented on src/components/SignUpPage/index.tsx
> +                      document.getElementsByName('pw')[0].focus();
[수정완료](https://github.com/GSM-MSG/GAUTH-frontend/pull/5/commits/69c1f66a722c946425713699154504ea4701c923)

2022-12-22 14:37 UTC, jjaejjae12 commented on src/components/SignUpPage/index.tsx
> +                      document.getElementsByName('email')[0].focus();
https://github.com/GSM-MSG/GAUTH-frontend/pull/5/commits/69c1f66a722c946425713699154504ea4701c923

2022-12-22 14:44 UTC, jjaejjae12 commented on src/components/LoginPage/style.ts
> +  position: absolute;
login페이지 반응형은 나중에 추가할 예정

2022-12-22 14:57 UTC, kangkong0805 commented on src/components/LoginPage/style.ts
> +  position: absolute;
저게 이메일 입력될 때 "@gsm.hs.kr" 를 추가해주는 component인데 입력될 때마다 추가하면 useState로 관리하기 어려워져서 따로 text를 분리해서 관리하고 있음.

input에서 입력한 text 바로 뒤에 "@gsm.hs.kr"를 띄우라는 디자인 요청사항이 있어서 입력될 때마다 위치 변화가 필요하기에 absolute를 줬음

2022-12-22 15:09 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +                }}
써봤는데 form제출할때 검사 하는 거여서 입력할 때 마다 검사할려면 change할때마다 검사 해여 할듯 그리고 찾아보니깐 if문 없이 change마다 정규식 적용할수 있길래 코드 수정

2022-12-22 15:21 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
>      }
경민이가 예외 처리 추가해서 고친데

2022-12-23 00:25 UTC, chanwoo00106 commented on src/components/LoginPage/style.ts
> +  position: absolute;
디자인이 어떤지는 잘 모르겠지만 요즘에는 아래와 같이 input 길이를 넉넉하게 만들어, 만약 글자 길이가 input 보다 길어진다고 해도 스크롤 되게만 함
<img width="320" alt="스크린샷 2022-12-23 오전 9 11 38" src="https://user-images.githubusercontent.com/57276315/209246203-71507286-5ee5-49b4-b22f-89c949256480.png">

그래서 결론은 absolute가 들어갈 필요가 없을 것 같은데?? 글고 입력될 때마다 위치 변화를 준다는 게 무슨 소린지 모르겠음

2022-12-23 00:27 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +                }}
또 event type이 any던데 이건 뭐야?

2022-12-23 00:29 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
>      }
도대체 태스크 분배를 어떻게 한거야?

2022-12-23 00:38 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
>      }
login부분이 경민 파트 signUp이 내 파트 지금 signUp branch에 login부분은 경민이가 나랑 겹치는 스타일이 많아서 전에 경민이가 merge한거 clone받아서 생긴부분임

2022-12-23 00:39 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +                }}
로그인 부분은 경민이 파트여서 signup부분만 고치는중

2022-12-23 01:04 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +                }}
그럼 왜 니 pr 경민이의 변경사항이 있는지 알려줄 수 있어?

2022-12-23 01:09 UTC, chanwoo00106 commented on src/components/LoginPage/style.ts
> +  position: absolute;
실행시켜서 확인 해 봤는데 그냥 위에 있는 것 처럼 오른쪽에 고정해도 될 것 같은데
지금 처럼 하면 gsm계정을 꼭 입력 해야 하는지 확인 할 방법이 email input에 입력 해봐야 알 수 있는 거잖아 이건 좀 불편한 것 같음

2022-12-23 01:10 UTC, chanwoo00106 commented on src/components/LoginPage/style.ts
> +  position: absolute;
심지어 맨 앞에 s가 입력이 안되는 데 이건 뭐야?

2022-12-23 01:20 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +                }}
commit보니깐 내가 따로 직접적으로 변경한건 없고 globalstyle수정할것도 있고 sidebar컴포넌트 추가한거랑 그 외에 loginbranch에서 변경했던거 필요해서 merge하고 pull받아서 그런듯

2022-12-23 01:33 UTC, kangkong0805 commented on src/components/LoginPage/style.ts
> +  position: absolute;
위위의 comment 참고할게

---

아마 한글 입력을 막은 정규식 때문에 "s"가 아닌 "ㄴ" 입력이 안 보여서 그런 것 같아
input style에서 
```css
ime-mode: inactive
```
를 추가하면 키보드 영문 모드가 default여서 수정할게

2022-12-23 01:46 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +                }}
pull을 받아도 develop에 같은 파일이 있으면 변경사항으로는 뜨지 않잖아

2022-12-23 02:07 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +                }}
어...다시 보니깐 그냥 prettire때문에 바뀐거 변경사항으로 뜬거 같아

2022-12-23 02:43 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +                }}
다음부턴 대신 한다고 해도 한 pr에 넣지는 말자

2022-12-23 02:45 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +                }}
확인 다른 부분 또 고쳐야할곳 있어?

2022-12-23 02:46 UTC, chanwoo00106 commented on src/components/LoginPage/style.ts
> +  position: absolute;
이거 다른 pr 에서 작업해줘

2022-12-23 02:47 UTC, chanwoo00106 approved these changes
더 막고 싶지만 이제는 눈으로만 봐선 안 보이네

2022-12-23 02:47 UTC, kangkong0805 commented on src/components/LoginPage/style.ts
> +  position: absolute;
확인

2022-12-23 03:00 UTC, merged