🔀 리디자인 추가
GSM-MSG/GAUTH-frontend pull request #60
Opened 2023-03-06 14:44 UTC by jjaejjae12

## 💡 개요
리디자인이 나와서 수정해주었다

##📃
* 회원가입 리디자인 추가
* 비번찾기 리디자인 추가
* 로그인 리디자인 추가
<img width="576" alt="image" src="https://user-images.githubusercontent.com/81688137/223143074-96f62b8f-1836-4e4c-b000-b11c5ff34312.png">

<img width="497" alt="image" src="https://user-images.githubusercontent.com/81688137/223143184-22e3a5c0-e756-4481-86b8-9e2dceed00bb.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/81688137/223143242-c488e656-bb29-4267-9be4-0f12a12c7110.png">

2023-03-06 15:10 UTC, kangkong0805 commented on src/components/NSignUp/Profile.tsx
> +// import { SubmitWrapper } from '../NewLoginPage/style';
주석 뭐야

2023-03-06 15:14 UTC, chanwoo00106 commented on src/components/NFindPsw/NewPassword.tsx
> +      if (!(e instanceof AxiosError)) return toast.error('unkonwn error');
이것 보단 axios에서 제공하는 isAxiosError를 사용 하는 것 도 좋을 것 같아

2023-03-06 15:15 UTC, kangkong0805 commented on src/components/NSignUp/style.ts
> +      }
```suggestion
          path {
            fill: #868e96;
          }
```
간단하게 수정했음

2023-03-06 15:19 UTC, kangkong0805 commented on src/types/errors.ts
> +export type errorTpye = {
errorType으로 고쳐주세요

2023-03-06 15:22 UTC, jjaejjae12 commented on src/components/NSignUp/Profile.tsx
> +// import { SubmitWrapper } from '../NewLoginPage/style';
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/deeed7b6c13ad1ba85a0b7f9b7bc1cd79efd1813)

2023-03-06 15:29 UTC, jjaejjae12 commented on src/types/errors.ts
> +export type errorTpye = {
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/6f4b6eb94235ce70628a6e4822869886e4e4770e)

2023-03-06 15:29 UTC, jjaejjae12 commented on src/components/NSignUp/style.ts
> +      }
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/9e6c5d4836b9cb03456e71e72cf7846e77fec8b0)

2023-03-06 15:40 UTC, jjaejjae12 commented on src/components/NFindPsw/NewPassword.tsx
> +      if (!(e instanceof AxiosError)) return toast.error('unkonwn error');
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/2d36b58122426842868079e3aeb98222289ae4f9)

2023-03-06 15:44 UTC, chanwoo00106 commented on src/components/NFindPsw/NewPassword.tsx
> +      if (!(e instanceof AxiosError)) return toast.error('unkonwn error');
이거 뿐만 아니라 모두 바꿔줘

2023-03-06 16:05 UTC, chanwoo00106 approved these changes

2023-03-06 16:05 UTC, chanwoo00106 commented on src/components/common/Auth/NewPasswordCommon.tsx
> +            <p onClick={() => changeModalType()}>{bottomPhrase}</p>
```suggestion
            <p onClick={changeModalType}>{bottomPhrase}</p>
```

2023-03-06 16:05 UTC, chanwoo00106 commented on src/components/common/Auth/VerifyEmail.tsx
> +        <button onClick={() => checkEmail()}>다음</button>
```suggestion
        <button onClick={checkEmail}>다음</button>
```

2023-03-06 16:05 UTC, chanwoo00106 commented on src/components/common/Loading/index.tsx
> +        })}
```suggestion
        {list.map((e) => (
          <S.span num={e} key={e} color={color} />
        ))}
```

이정도로 줄일 수 있을 듯

2023-03-06 16:12 UTC, jjaejjae12 commented on src/components/NewSignIn/index.tsx
> +      localStorage.setItem(expiredAt, data.expiresAt);
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/22cf806286e5e47a2dcd89ff7d0ba4cc50d467df)

2023-03-06 16:16 UTC, jjaejjae12 commented on src/components/NewSignUp/Notion.tsx
> +  }, []);
[수정[(https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/1319efa3adf4bf752b8884c94233b5de3e85e94b)

2023-03-06 16:16 UTC, jjaejjae12 commented on src/components/NFindPsw/NewPassword.tsx
> +      if (!(e instanceof AxiosError)) return toast.error('unkonwn error');
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/800fe8d3ffe7186ec786074ea34310736192bd61)

2023-03-06 16:43 UTC, jjaejjae12 commented on src/components/NewSignUp/Profile.tsx
> +          multiple
지워도 [될듯](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/3efbe5688e1e6f059ccfab233b845f2185977358)

2023-03-06 23:50 UTC, chanwoo00106 commented on src/components/LoginPage/index.tsx
> +import axios, { AxiosError } from 'axios';
isAxiosError를 바로 import 하는 건 어때?

2023-03-07 06:15 UTC, jjaejjae12 commented on src/components/LoginPage/index.tsx
> +import axios, { AxiosError } from 'axios';
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/ef9f3857eac0e8b6bc5930e47be08723b16ccec6)

2023-03-07 06:23 UTC, jjaejjae12 commented on src/components/NewSignIn/index.tsx
> +    );
[이런](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/e86ee9434409037cc939e7268d386a8576bf1b7c)식으로 바꿔봄

2023-03-07 06:33 UTC, jjaejjae12 commented on src/components/NewSignIn/index.tsx
> +    );
바꾼걸 다시 [바꿔봄](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/2991a508967fc8765dbce45fd9ddf40ba65ad4cf)

2023-03-07 10:51 UTC, kangkong0805 commented on src/components/common/Auth/SearchEmail.tsx
> +    router.query.redirect_uri !== undefined;
```suggestion
    router.query[client_id] !== undefined &&
    router.query[redirect_uri] !== undefined;
```
just refectoring

2023-03-07 10:56 UTC, kangkong0805 commented on src/components/common/Loading/style.ts
> +  transform: rotateX(90deg) translateZ(-25px);
```suggestion
export const span = styled.span<placedprop>`
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(rgba(100, 100, 255), ${(props) => props.color});
  transform: rotateY(calc(90deg * var(--i))) translateZ(25px);
  --i: ${(prop) => prop.num};
`;

export const top = styled(span)`
  width: 50px;
  height: 50px;
  background-color: rgba(100, 100, 255);
  transform: rotateX(90deg) translateZ(25px);
`;
export const bottom = styled(top)`
  top: 100%;
  background-color: #00ccff;
  transform: rotateX(90deg) translateZ(-25px);
```
just refectoring2 (이상해보이면 실행 ㄱㄱ)

2023-03-07 11:18 UTC, jjaejjae12 commented on src/components/common/Loading/style.ts
> +  transform: rotateX(90deg) translateZ(-25px);
이상해서 일케 [바꿈](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/d5ed0cb94949e6a782abfc25ab72fd5ea58c6cee) + 반응형

2023-03-07 23:07 UTC, chanwoo00106 commented on src/api/TokenManger.ts
>        if (skipUrl.includes(Router.route)) {
2중 if 선넘네

2023-03-07 23:21 UTC, chanwoo00106 commented on src/components/NewFindPsw/NewPassword.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
에러 메시지를 바꿀 필요가 있을 것 같은데?

2023-03-07 23:21 UTC, chanwoo00106 commented on src/types/index.ts
> +export * from './errors';
대문자 사이에 소문자네

2023-03-07 23:21 UTC, chanwoo00106 commented on src/types/errors.ts
> +export type errorType = {
camel uppercase로 하는 게 좋을 듯

2023-03-07 23:43 UTC, jjaejjae12 commented on src/api/TokenManger.ts
>        if (skipUrl.includes(Router.route)) {
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/5aa27d3588229a6651a6e59121000f0df23c257b)

2023-03-07 23:49 UTC, jjaejjae12 commented on src/components/NewFindPsw/NewPassword.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
추가를 하라는 말임 메시지 문구를 바꾸라는 말임?

2023-03-07 23:53 UTC, jjaejjae12 commented on src/types/index.ts
> +export * from './errors';
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/2864ee160ab806f530c0a4c5eb7ada3f4f766dfb)

2023-03-07 23:53 UTC, jjaejjae12 commented on src/types/errors.ts
> +export type errorType = {
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/2864ee160ab806f530c0a4c5eb7ada3f4f766dfb)

2023-03-07 23:54 UTC, jjaejjae12 commented on src/components/NewFindPsw/NewPassword.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
일단 일케 [바꿈](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/5c863926b43adccd5a9fe47bddbd6f59d8a8f6fa)

2023-03-08 01:39 UTC, chanwoo00106 approved these changes

2023-03-08 01:41 UTC, chanwoo00106 requested changes

2023-03-08 01:41 UTC, chanwoo00106 commented on src/components/NewFindPsw/NewPassword.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
차라리 한글로 메시지를 띄워줘

2023-03-08 02:33 UTC, jjaejjae12 commented on src/components/NewFindPsw/NewPassword.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
에러 처리가 미흡한거 같아서 추가해줌

2023-03-08 02:40 UTC, jjaejjae12 commented
한글로 변경했어

2023-03-08 04:02 UTC, chanwoo00106 commented on src/components/NewSignUp/Notion.tsx
> +  const NOTION_INSTRUCTIOM_PAGE_ID = '1386310822b1406695bc604ba28821e2';
상수는 다른 곳에 선언해야 할 것 같아

2023-03-08 04:03 UTC, chanwoo00106 commented on src/components/NewSignUp/Notion.tsx
> +        if (!isAxiosError(e)) return toast.error('unkonwn error');
아직 한 발 남았다

2023-03-08 04:03 UTC, chanwoo00106 commented on src/components/NewSignUp/Profile.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
아직 두 발 남았다

2023-03-08 04:04 UTC, chanwoo00106 commented on src/components/common/Auth/SearchEmail.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
아직 세 발 남았다

2023-03-08 04:30 UTC, jjaejjae12 commented on src/components/NewSignUp/Notion.tsx
> +  const NOTION_INSTRUCTIOM_PAGE_ID = '1386310822b1406695bc604ba28821e2';
[수정](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/876e842534f83f13f9e9dfc36bab6acf320a0523)

2023-03-08 04:31 UTC, jjaejjae12 commented on src/components/NewSignUp/Notion.tsx
> +        if (!isAxiosError(e)) return toast.error('unkonwn error');
[이거 방탄 유리야](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/65cc812c5b51b131a922535b68ee721bd1d97931)

2023-03-08 04:32 UTC, jjaejjae12 commented on src/components/NewSignUp/Profile.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
[이거 방탄 유리야](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/65cc812c5b51b131a922535b68ee721bd1d97931)

2023-03-08 04:32 UTC, jjaejjae12 commented on src/components/common/Auth/SearchEmail.tsx
> +      if (!isAxiosError(e)) return toast.error('unkonwn error');
[이거 방탄 유리야](https://github.com/GSM-MSG/GAUTH-frontend/pull/60/commits/65cc812c5b51b131a922535b68ee721bd1d97931)

2023-03-08 08:46 UTC, chanwoo00106 approved these changes

2023-03-08 08:48 UTC, kangkong0805 approved these changes

2023-03-08 08:51 UTC, merged